---
# This lab blueprint includes a 
# - DC01 : Windows Domain controller / jumphost
# - VCSA : vCenter Server Virtual Appliance
# - ESXi01 - ESXi04 : (4) nested ESXi hosts
#
# Sufficient resources to construct a 4-node vSAN
# and complete ICM level workflows

- name: Build Lab - vSphere7
  hosts: localhost
  gather_facts: false
  vars:
    lab_name: lab_vsphere7
    lab_password: P@ssw0rd
    lab_network_wan_portgroup: "VM Network"
    lab_network_lan1_portgroup: "lab_vsphere7_net1"
    lab_network_lan1_netmask_cidr: "24"
    lab_network_lan1_netmask: "255.255.255.0"
    lab_network_lan1_gateway: "192.168.0.1"
    lab_network_lan1_dns_ip: "192.168.0.1"
    lab_domain_name: "lab.local"
    lab_dc01_hostname: "dc01"
    lab_dc01_ip: "192.168.0.11"
    lab_vcsa_hostname: "vcsa"
    lab_vcsa_ip: "192.168.0.50"
    lab_esx01_hostname: "esxi01"
    lab_esx01_ip: "192.168.0.51"
    lab_esx02_hostname: "esxi02"
    lab_esx02_ip: "192.168.0.52"
    lab_esx03_hostname: "esxi03"
    lab_esx03_ip: "192.168.0.53"
    lab_esx04_hostname: "esxi04"
    lab_esx04_ip: "192.168.0.54" 
    lab_create_local_vmfs: 'False'
    lab_vcsa_autoconfigure: 'True'
    lab_vsca_fqdn_or_ip: "vcsa.lab.local" 
    lab_vm_datastore: lab_vsphere7
# skip flags for debugging
    # skip_gateway_vm: true
    # skip_dc01_vm: true
    # skip_vcsa_vm: true
    # skip_esx01_vm: true
    # skip_esx02_vm: true
    # skip_esx03_vm: true
    # skip_esx04_vm: true
  vars_files: 
    - vars/vars-esx.yml
  tasks:
    - name: Build lab pfSense Gateway
      block:
      - include_vars: defaults/Build_pfSense_from_ISO.yml
      - include_tasks: tasks/Build_pfSense_from_ISO.yml
        vars:
          vm_name: '{{lab_name}}_gateway'
          vm_datastore: "{{lab_vm_datastore}}"
          vm_password_new: "{{lab_password}}"
          vm_network_wan: "{{lab_network_wan_portgroup}}"
          vm_network_lan: "{{lab_network_lan1_portgroup}}"
          config_xml_file: "files/pfsense/config.xml"
      when: skip_gateway_vm is not true

    - name: Build Windows VM - DC01
      block:
      - include_vars: defaults/Build_Windows_VM_from_ISO.yml
      - include_tasks: tasks/Build_Windows_VM_from_ISO.yml
        vars:
          vm_name: '{{lab_name}}_{{lab_dc01_hostname}}'         
          vm_datastore: "{{lab_vm_datastore}}"
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_password_new: "{{lab_password}}"
          vm_hostname: "{{lab_dc01_hostname}}"
          vm_address: "{{lab_dc01_ip}}"
          vm_netmask_cidr: "{{lab_network_lan1_netmask_cidr}}"
          vm_gateway: "{{lab_network_lan1_gateway}}"
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
      when: skip_dc01_vm is not true

    - name: Build a Active Directory Forest
      block:
      - include_tasks: tasks/Create_New_Active_Directory_using_vm_shell.yml
        vars:
          vm_name: '{{lab_name}}_{{lab_dc01_hostname}}'
          vm_username: ".\\Administrator" 
          vm_password: "{{lab_password}}"         
          vm_dns_server: "{{lab_network_lan1_dns_ip}}"
          vm_domain: "{{lab_domain_name}}"
      when: skip_dc01_vm is not true    

    - name: Perform additional configuration steps on DC01
      community.vmware.vmware_vm_shell:
        hostname: '{{ vcenter_address }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}' 
        validate_certs: no
        vm_username: ".\\Administrator"
        vm_password: "{{lab_password}}"
        vm_id: '{{lab_name}}_{{lab_dc01_hostname}}'
        vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
        vm_shell_args: " -command \"({{item}})\""
        wait_for_process: true
      delegate_to: localhost
      retries: 6
      delay: 10 
      register: result           
      until: result is succeeded 
      when: skip_dc01_vm is not true    
      loop:
        # Add vCenter DNS record    
        - "Add-DnsServerResourceRecordA -Name {{lab_vcsa_hostname}} -ZoneName {{lab_domain_name}} -AllowUpdateAny -IPv4Address {{lab_vcsa_ip}} -TimeToLive 01:00:00"
        # Add ESX01 DNS record
        - "Add-DnsServerResourceRecordA -Name {{lab_esx01_hostname}} -ZoneName {{lab_domain_name}} -AllowUpdateAny -IPv4Address {{lab_esx01_ip}} -TimeToLive 01:00:00"
        # Add ESX01 DNS record
        - "Add-DnsServerResourceRecordA -Name {{lab_esx02_hostname}} -ZoneName {{lab_domain_name}} -AllowUpdateAny -IPv4Address {{lab_esx02_ip}} -TimeToLive 01:00:00"
        # Add ESX01 DNS record
        - "Add-DnsServerResourceRecordA -Name {{lab_esx03_hostname}} -ZoneName {{lab_domain_name}} -AllowUpdateAny -IPv4Address {{lab_esx03_ip}} -TimeToLive 01:00:00"
        # Add ESX01 DNS record
        - "Add-DnsServerResourceRecordA -Name {{lab_esx04_hostname}} -ZoneName {{lab_domain_name}} -AllowUpdateAny -IPv4Address {{lab_esx04_ip}} -TimeToLive 01:00:00"
        # Disable Admin IEESC
        - "set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}' -name IsInstalled -Value 0"
        # Disable User IEESC
        - "set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components{A509B1A8-37EF-4b3f-8CFC-4F3A74704073}' -name IsInstalled -Value 0"

# Deploy vCenter
    - name: Build vCenter Appliance from OVA
      block:
      - include_vars: defaults/Build_vCenter_from_OVA.yml
      - include_tasks: tasks/Build_vCenter_from_OVA.yml
        vars:
          # ova_file: "files/VMware/VMware-vCenter-Server-Appliance-7.0.1.00200-17327517_OVF10.ova"
          vm_name: '{{lab_name}}_{{lab_vcsa_hostname}}'
          vm_hostname: '{{lab_vcsa_hostname}}'
          vm_domain: '{{lab_domain_name}}'
          vm_fqdn: '{{lab_vsca_fqdn_or_ip}}'  # if no DNS resolution, use the IP address here
          vm_network: '{{lab_network_lan1_portgroup}}'
          vm_password: '{{lab_password}}'
          vm_net_mode: "static" # static or dhcp
          vm_address: '{{lab_vcsa_ip}}'
          vm_netmask_cidr: '{{lab_network_lan1_netmask_cidr}}'
          vm_dns_server: '{{lab_network_lan1_dns_ip}}'
          vm_gateway: '{{lab_network_lan1_gateway}}'
          # searchpath: ""
          # vm_deployment_size: 'tiny' 
          vm_autoconfig: '{{lab_vcsa_autoconfigure}}'
          # vm_enable_ssh: 'True'
      when: skip_vcsa_vm is not true

    # Deploy ESX101
    - name: Build Nested ESXI from OVA
      block:
      - include_vars: defaults/Build_Nested_ESXi_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_{{lab_esx01_hostname}}'
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_memory_mb: 8192
          vm_num_cpus: 2
          vm_disk1_size_gb: 4
          vm_disk2_size_gb: 40
          #ovf_file: "files/VMware/Nested_ESXi7.0_Appliance_Template_v1.ova"
          ovf_hostname: "{{lab_esx01_hostname}}"
          ovf_address: "{{lab_esx01_ip}}"
          ovf_netmask: "{{lab_network_lan1_netmask}}"
          ovf_gateway: "{{lab_network_lan1_gateway}}"
          ovf_vlan: ""  
          ovf_dns: "{{lab_network_lan1_dns_ip}}" 
          ovf_domain: "{{lab_domain_name}}"   
          ovf_ntp: "{{lab_network_lan1_gateway}}"
          ovf_syslog: "" # IP of syslog server
          ovf_password: "{{lab_password}}"
          ovf_ssh: "true"
          ovf_createvmfs: "{{lab_create_local_vmfs}}"
      - include_tasks: tasks/Build_Nested_ESXi_from_OVA.yml
      when: skip_esx01_vm is not true

    # DEPLOY ESXi02
    - name: Build Nested ESXI from OVA
      block:
      - include_vars: defaults/Build_Nested_ESXi_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_{{lab_esx02_hostname}}'
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_memory_mb: 8192
          vm_num_cpus: 2
          vm_disk1_size_gb: 4
          vm_disk2_size_gb: 40
          ovf_file: "files/VMware/Nested_ESXi7.0_Appliance_Template_v1.ova"
          ovf_hostname: "{{lab_esx02_hostname}}"
          ovf_address: "{{lab_esx02_ip}}"
          ovf_netmask: "{{lab_network_lan1_netmask}}"
          ovf_gateway: "{{lab_network_lan1_gateway}}"
          ovf_vlan: ""  
          ovf_dns: "{{lab_network_lan1_dns_ip}}" 
          ovf_domain: "{{lab_domain_name}}"  
          ovf_ntp: "{{lab_network_lan1_gateway}}"
          ovf_syslog: "" # IP of syslog server
          ovf_password: "{{lab_password}}"
          ovf_ssh: "true"
          ovf_createvmfs: "{{lab_create_local_vmfs}}"
      - include_tasks: tasks/Build_Nested_ESXi_from_OVA.yml
      when: skip_esx02_vm is not true

# DEPLOY ESX3
    - name: Build Nested ESXI from OVA
      block:
      - include_vars: defaults/Build_Nested_ESXi_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_{{lab_esx03_hostname}}'
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_memory_mb: 8192
          vm_num_cpus: 2
          vm_disk1_size_gb: 4
          vm_disk2_size_gb: 40
          #ovf_file: "files/VMware/Nested_ESXi7.0_Appliance_Template_v1.ova"
          ovf_hostname: "{{lab_esx03_hostname}}"
          ovf_address: "{{lab_esx03_ip}}"
          ovf_netmask: "{{lab_network_lan1_netmask}}"
          ovf_gateway: "{{lab_network_lan1_gateway}}"
          ovf_vlan: ""  
          ovf_dns: "{{lab_network_lan1_dns_ip}}" 
          ovf_domain: "{{lab_domain_name}}"  
          ovf_ntp: "{{lab_network_lan1_gateway}}"
          ovf_syslog: "" # IP of syslog server
          ovf_password: "{{lab_password}}"
          ovf_ssh: "true"
          ovf_createvmfs: "{{lab_create_local_vmfs}}"
      - include_tasks: tasks/Build_Nested_ESXi_from_OVA.yml
      when: skip_esx03_vm is not true

# DEPLOY ESX4
    - name: Build Nested ESXI from OVA
      block:
      - include_vars: defaults/Build_Nested_ESXi_from_OVA.yml
      - set_fact:
          vm_name: '{{lab_name}}_{{lab_esx04_hostname}}'
          vm_network: "{{lab_network_lan1_portgroup}}"
          vm_memory_mb: 8192
          vm_num_cpus: 2
          vm_disk1_size_gb: 4
          vm_disk2_size_gb: 40
          ovf_file: "files/VMware/Nested_ESXi7.0_Appliance_Template_v1.ova"
          ovf_hostname: "{{lab_esx04_hostname}}"
          ovf_address: "{{lab_esx04_ip}}"
          ovf_netmask: "{{lab_network_lan1_netmask}}"
          ovf_gateway: "{{lab_network_lan1_gateway}}"
          ovf_vlan: ""  
          ovf_dns: "{{lab_network_lan1_dns_ip}}" 
          ovf_domain: "{{lab_domain_name}}"  
          ovf_ntp: "{{lab_network_lan1_gateway}}"
          ovf_syslog: "" # IP of syslog server
          ovf_password: "{{lab_password}}"
          ovf_ssh: "true"
          ovf_createvmfs: "{{lab_create_local_vmfs}}"
      - include_tasks: tasks/Build_Nested_ESXi_from_OVA.yml
      when: skip_esx04_vm is not true

    


