---
- name: "Install Required Python Modules"
  hosts: localhost
  gather_facts: false
  vars_files:
#    vars/main.yml
  tasks:

  - name: install python modules
    ansible.builtin.pip:
      name: "{{item}}"
    with_items:
      - pycdlib
      
