---
- name: Build StorageGrid from OVA
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yml
  vars:
    #ovf_version: "11.5.0"
    grid_name: "test2-sgws"
    grid_network_name: "VM Network"
    grid_network_config: "STATIC"
    grid_network_mask: "255.255.255.0"
    grid_network_gateway: "192.168.123.1"
    admin_ip: 192.168.123.170

  tasks:
    # Deploy Admin Node
    - include_role: 
        name: deploy_ovf_storagegrid
      vars:
        node_type: "VM_Admin_Node"   
        vm_name:      "{{grid_name}}-admin"
        ovf_hostname: "{{grid_name}}-admin"
        grid_network_ip: "{{admin_ip}}"               
        vm_memory_mb: 12288
        vm_num_cpus: 2

    # Deploy Storage Node 1
    - include_role: 
        name: deploy_ovf_storagegrid
      vars:
        node_type:    "VM_Storage_Node"        
        vm_name:      "{{grid_name}}-storage1"
        ovf_hostname: "{{grid_name}}-storage1"
        grid_network_ip: "192.168.123.171"               
        vm_memory_mb: 8192
        vm_num_cpus: 1

    # # Deploy Storage Node 2
    - include_role: 
        name: deploy_ovf_storagegrid
      vars:
        node_type:    "VM_Storage_Node"        
        vm_name:      "{{grid_name}}-storage2"
        ovf_hostname: "{{grid_name}}-storage2"
        grid_network_ip: "192.168.123.172"               
        vm_memory_mb: 8192
        vm_num_cpus: 1

    # # Deploy Storage Node 3
    - include_role: 
        name: deploy_ovf_storagegrid
      vars:
        node_type:    "VM_Storage_Node"        
        vm_name:      "{{grid_name}}-storage3"
        ovf_hostname: "{{grid_name}}-storage3"
        grid_network_ip: "192.168.123.173"               
        vm_memory_mb: 8192
        vm_num_cpus: 1

    # Deploy Gateway Node
    - include_role: 
        name: deploy_ovf_storagegrid
      vars:
        node_type:    "VM_API_Gateway"        
        vm_name:      "{{grid_name}}-gateway"
        ovf_hostname: "{{grid_name}}-gateway"
        grid_network_ip: "192.168.123.174"               
        vm_memory_mb: 8192
        vm_num_cpus: 1

    # Deploy Non-Primary Admin Node
    - include_role: 
        name: deploy_ovf_storagegrid
      vars:
        node_type: "VM_Admin_Node"
        admin_role: "Non-Primary"      
        vm_name:      "{{grid_name}}-admin2"
        ovf_hostname: "{{grid_name}}-admin2"
        grid_network_ip: "192.168.123.175"               
        vm_memory_mb: 8192
        vm_num_cpus: 1


