---
- hosts: localhost 
  name: Build ONTAP Simulator from OVA
  gather_facts: false
  vars_files: 
    - vars/main.yml
  tasks:
#    - include_vars: defaults/Build_ONTAP_Simulator_from_OVA.yml
    - include_tasks: tasks/Build_ONTAP_Simulator_from_OVA.yml
      vars:
        vm_name: TEST_vsim194
        sys_serial_number: "4034389-06-2"
        ontap_node_mgmt_ip: "192.168.123.194"
        ontap_netmask: "255.255.255.0"
        ontap_gateway: "192.168.123.1"
