---
- name: Prepare for DCPromo
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}' 
    validate_certs: no
    vm_username: "{{vm_username}}"
    vm_password: "{{ vm_password }}"
    vm_id: "{{ vm_name }}"
    vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
    vm_shell_args: " -command \"({{item}})\""
    wait_for_process: true
  delegate_to: localhost
  register: checkdc    
  ignore_errors: true         
  loop:
    - "$result=$(if($($osInfo = Get-WmiObject -Class Win32_OperatingSystem;$osInfo.ProductType) -ne 2){throw})"

- name: DCPromo
  block:   
  - name: Prepare for DCPromo
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}' 
      validate_certs: no
      vm_username: "{{vm_username}}"
      vm_password: "{{ vm_password }}"
      vm_id: "{{ vm_name }}"
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: " -command \"({{item}})\""
      wait_for_process: true
    delegate_to: localhost
    retries: 3
    delay: 10 
    register: result           
    until: result is succeeded    
    loop:
      # Configure upstream DNS via vmware_vm_shell      
      - "Set-DnsClientServerAddress -InterfaceAlias Ethernet0 -ServerAddresses {{ vm_dns_server }}"
      # Install AD-Domain-Services
      - "Install-windowsfeature AD-Domain-Services -IncludeAllSubFeature -IncludeManagementTools"
      # Install DNS
      #- "Install-windowsfeature DNS -IncludeAllSubFeature -IncludeManagementTools"
      # Install RSAT-ADDS        
      - "Install-windowsfeature RSAT-ADDS"
      # Unrestrict remote scripts
      - "Set-ExecutionPolicy unrestricted"

  - name: Create Domain
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}' 
      validate_certs: no
      vm_username: "{{vm_username}}"
      vm_password: "{{ vm_password }}"
      vm_id: "{{ vm_name }}"
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: " -command \"({{item}})\""
      wait_for_process: true
    delegate_to: localhost
    loop:
      - "Import-module addsdeployment"
      - "Install-ADDSForest -DomainName {{vm_domain}} -CreateDnsDelegation:$false -InstallDNS:$true -NoRebootOnCompletion:$true -DatabasePath C:\\Windows\\NTDS -LogPath C:\\Windows\\NTDS -SysvolPath C:\\Windows\\SYSVOL -SafeModeAdministratorPassword $(convertto-securestring {{ vm_password }} -AsPlainText -Force:$true) -Force:$true -WarningAction silentlyContinue"
    retries: 6
    delay: 60
    register: result           
    until: result is succeeded    
    ignore_errors: yes #This step always returns a vix error
  #X C:\> Install-ADDSForest
  ##  -CreateDnsDelegation:$false `
  ##  -DatabasePath "C:\Windows\NTDS" `
  #  -DomainMode "Win2016" `
  #X  -DomainName "yourdomain.com" `
  #  -DomainNetbiosName "THEGEEKSTUFF" `
  #  -ForestMode "Win2016" `
  #X  -InstallDns:$true `
  ##  -LogPath "C:\Windows\NTDS" `
  ##  -NoRebootOnCompletion:$false `
  ##  -SysvolPath "C:\Windows\SYSVOL" `
  ##  -Force:$true

  - name: Reboot-Guest
    vmware_guest_powerstate:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}' 
      validate_certs: no
      name: '{{ vm_name }}'
      state: reboot-guest
    delegate_to: localhost
    register: deploy
  - name: Wait for 60 seconds
    wait_for: timeout=60
    delegate_to: localhost
  - name: Wait for VMware tools to become available by name
    vmware_guest_tools_wait:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}' 
      validate_certs: no
      name: '{{ vm_name }}'
    delegate_to: localhost
    retries: 3
    delay: 15
    register: result           
    until: result is succeeded 
  - name: Wait for 30 seconds for VMware Tools refresh
    wait_for: timeout=30
    delegate_to: localhost

  - name: Perform additional configuration steps
    community.vmware.vmware_vm_shell:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}' 
      validate_certs: no
      vm_username: "{{vm_username}}"
      vm_password: "{{ vm_password }}"
      vm_id: "{{ vm_name }}"
      vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
      vm_shell_args: " -command \"({{item}})\""
      wait_for_process: true
    delegate_to: localhost
    retries: 6
    delay: 10 
    register: result           
    until: result is succeeded     
    loop:
      # Assign dns server to itself      
      - "Set-DnsClientServerAddress -InterfaceAlias Ethernet0 -ServerAddresses 127.0.0.1"
      # re-enable remote desktop
      - "set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server' -name fDenyTSConnections -Value 0"
      # re-add the remote desktop firewall fule
      - "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
      # Disable firewall for Domain, Public and Private profiles
      - "Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False"

  when: checkdc is failed
# scriptlet for adding dns records
#Add-DnsServerResourceRecordA -Name "host23" -ZoneName "contoso.com" -AllowUpdateAny -IPv4Address "172.18.99.23" -TimeToLive 01:00:00


