---
# - name: Install xRDP on Centos8 via vm_shell
#   hosts: localhost
#   gather_facts: false
#   vars:
#     vm_name: TEST_Centos8VM
#     vm_username: root
#     vm_password: P@ssw0rd
#   vars_files: 
#     - vars/main.yml
#   tasks:
- name: Install xRDP on Centos8
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{vm_username}}"
    vm_password: '{{ vm_password }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"{{item}}\""
    wait_for_process: true
  delegate_to: localhost  
  loop:
    - "dnf install -y epel-release"
    - "dnf install -y xrdp"
    - "xrdp-keygen xrdp auto"
    - "systemctl enable xrdp --now"
    - "firewall-cmd --permanent --add-port=3389/tcp"
    - "firewall-cmd --reload"
