- name: Run extra commands in powershell
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    vm_username: '{{ vm_username }}'
    vm_password: '{{ vm_password_new }}'
    vm_id:       '{{ vm_name }}'
    vm_shell:    'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
    vm_shell_args: " -command \"({{item}})\""
    wait_for_process: true
  delegate_to: localhost
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  ignore_errors: true
  loop: "{{extra_commands}}"
  when: extra_commands is defined
  