---
# - name: Install Ansible on Centos7 via vm_shell
#   hosts: localhost
#   gather_facts: false
#   vars:
#     vm_name: TEST_Centos7VM
#     vm_username: root
#     vm_password: P@ssw0rd
#   vars_files: 
#     - vars/main.yml
#   tasks:
- name: Install Ansible and related components
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{ vm_username | default('root') }}"
    vm_password: '{{ vm_password }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"{{item}}\""
    wait_for_process: true
  delegate_to: localhost  
  loop:
    - "dnf install -y epel-release"
    - "dnf install -y ansible"
    - "dnf install -y python-pip"
    - "dnf install -y python-devel"
    - "dnf groupinstall -y 'development tools'"
    - "pip install netapp-lib"
    - "pip install pyvmomi"
    - "pip install pywinrm"
    - "pip install pycdlib" 
