---
- name: variable defaults
  set_fact:
    vm_address:      "{{vm_address      | default('') }}"
    vm_netmask_cidr: "{{vm_netmask_cidr | default('') }}"
    vm_gateway:      "{{vm_gateway      | default('') }}"
    vm_dns_server:   "{{vm_dns_server   | default('') }}"
    vm_domain:       "{{vm_domain       | default('') }}"
    vm_hostname:     "{{vm_hostname     | default('centosvm') }}"
    vm_name:         "{{vm_name         | default('centosvm') }}"
    vm_eth_name:     "{{vm_eth_name     | default('ens32') }}"
    vm_username:     "ubuntu"
    # vm_password:     "P@ssw0rd2"
    vm_password_old: "ubuntu" #"{{cloudinit_password | default('Changeme!') }}"
    vm_password:     "{{ vm_password | default('P@ssw0rd') }}"
    config_iso:      "{{ vm_name }}-seed.iso"
    dnf_or_yum:      "yum"

- name: Create kickstart ISO
  community.general.iso_create:
    dest_iso: "{{ role_path }}/files/{{config_iso}}"    
    src_files:
      - "{{ cloudinit_userdata }}"
      - "{{ cloudinit_metadata }}"
    interchange_level: 4
    joliet: 3
    vol_ident: cidata
  delegate_to: localhost

- name: Copy kickstart iso to datastore
  community.vmware.vsphere_copy:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'  
    validate_certs: no 
    src: "{{ role_path }}/files/{{config_iso}}"
    datacenter: "{{vcenter_datacenter}}"
    datastore: "{{ vm_datastore }}"
    path: "{{config_iso}}"
  delegate_to: localhost
  ignore_errors: true #if the playbook is being re-run while the vm is on, the iso cannot be replaced

- name: Check if install ISO exists
  community.vmware.vsphere_file:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no
    datacenter: "{{vcenter_datacenter}}"
    datastore: "{{ iso_datastore }}"
    path: "{{ install_iso }}"
    state: file
  register: install_iso_exists
  delegate_to: localhost
  ignore_errors: true 

- name: Copy install iso to datastore
  community.vmware.vsphere_copy:
    hostname:   "{{ vcenter_address }}"
    username:   "{{ vcenter_username }}"
    password:   "{{ vcenter_password }}"
    validate_certs: no 
    src:        "{{ role_path }}/files/{{install_iso}}"
    datacenter: "{{ vcenter_datacenter}}"
    datastore:  "{{ iso_datastore }}"
    path:       "{{ install_iso }}"
  delegate_to: localhost
  ignore_errors: true #if the playbook is being re-run while the vm is on, the iso cannot be replaced
  when: install_iso_exists.failed

- name: Check if install ISO exists
  community.vmware.vsphere_file:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no
    datacenter: "{{vcenter_datacenter}}"
    datastore: "{{ iso_datastore }}"
    path: "{{ install_iso }}"
    state: file
  register: install_iso_exists
  delegate_to: localhost
  ignore_errors: true 

- name: If the ISO is not present have ESXi download it
  block:
  - name: Add ESXi to Ansible Hosts for SSH
    add_host:
      name: '{{ esxi_address }}'
      group: "esx"
      ansible_user: '{{ esxi_username }}'
      ansible_password: '{{ esxi_password }}'
      ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  - name: Enable ESX SSH (TSM-SSH)
    community.vmware.vmware_host_service_manager:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'   
      validate_certs: no 
      esxi_hostname: '{{ esxi_hostname }}'
      service_name: TSM-SSH
      state: present
    register: tsm_ssh_service
    delegate_to: localhost

  - name: Enable ESX Shell (TSM)
    community.vmware.vmware_host_service_manager:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'    
      validate_certs: no 
      esxi_hostname: '{{ esxi_hostname }}'
      service_name: TSM
      state: present
    register: tsm_service
    delegate_to: localhost

  - name: Download the Centos ISO
    shell: 'wget -P /vmfs/volumes/{{ iso_datastore }} {{ install_iso_url }}'
    args:
      creates: '/vmfs/volumes/{{ iso_datastore }}/{{ install_iso }}'
    delegate_to: '{{ esxi_address }}'

  - name: Disable ESX SSH (TSM-SSH)
    community.vmware.vmware_host_service_manager:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'    
      validate_certs: no 
      esxi_hostname: '{{ esxi_hostname }}'
      service_name: TSM-SSH
      state: absent
    delegate_to: localhost
    when: tsm_ssh_service.changed

  - name: Disable ESX Shell (TSM)
    community.vmware.vmware_host_service_manager:
      hostname: '{{ vcenter_address }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'   
      validate_certs: no 
      esxi_hostname: '{{ esxi_hostname }}'
      service_name: TSM
      state: absent
    delegate_to: localhost
    when: tsm_service.changed
  when: install_iso_exists.failed
## End Block

- name: Create VM
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}' 
    validate_certs: no 
    datacenter: "{{vcenter_datacenter}}"
    cluster: '{{vcenter_cluster}}'    
    folder: /
    name: '{{ vm_name }}'
    state: present
    guest_id: centos7_64Guest
    cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '[{{ iso_datastore }}] {{ install_iso }}'
        - controller_number: 0
          unit_number: 1
          state: present
          type: iso
          iso_path: '[{{ vm_datastore }}] {{config_iso}}'
    disk:
    - size_gb: '{{ vm_disk_gb | default(40) }}'
      type: thin
      datastore: '{{ vm_datastore }}'
    hardware:
      memory_mb: '{{ vm_memory_mb | default(2048) }}'
      num_cpus: '{{ vm_num_cpus | default(2) }}'
      scsi: lsilogicsas
    networks:
    - name: "{{ vm_network | default('VM Network') }}"
      device_type: e1000
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy_vm

- name: Set boot order
  community.vmware.vmware_guest_boot_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no  
    name: '{{ vm_name }}'
    boot_delay: 1000
    enter_bios_setup: False
    boot_retry_enabled: True
    boot_retry_delay: 20000
    boot_firmware: bios
    secure_boot_enabled: False
    boot_order:
      - disk
      - cdrom
      - ethernet
      - floppy
  delegate_to: localhost
  register: vm_boot_order

- name: Power-On the virtual machine
  community.vmware.vmware_guest_powerstate:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'    
    validate_certs: no 
    name: '{{ vm_name }}'
    state: powered-on
  delegate_to: localhost
  register: powerstate

- name: Wait for 120 seconds for cloudinit
  wait_for: timeout=120
  delegate_to: localhost

- name: type yes
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "yes"
  delegate_to: localhost

- name: press enter
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: ENTER
  delegate_to: localhost

- name: Wait for VMware tools to become available 
  community.vmware.vmware_guest_tools_wait:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    name: '{{ vm_name }}'
  delegate_to: localhost
  retries: 10
  delay: 60
  register: result           
  until: result is succeeded

- name: Wait for 15 minutes for cloudinit
  wait_for: timeout=900
  delegate_to: localhost

- name: Set ubuntu Passwd
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'    
    validate_certs: no 
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password_old }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: "-c \"echo -e '{{vm_password_old}}\n{{vm_password}}\n{{vm_password}}' | passwd \""
    wait_for_process: true
  delegate_to: localhost
  ignore_errors: yes   

- name: Check Hostname
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"[ $(hostname) == {{ vm_hostname }}.{{ vm_domain }} ]\""
    wait_for_process: true
  register: checkhostname
  delegate_to: localhost 
  ignore_errors: true 

- name: Configure network with nmcli
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    vm_username: "{{ vm_username }}"
    vm_password: '{{ vm_password }}'
    vm_id: '{{ vm_name }}'
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"{{item}}\""
    wait_for_process: true
  delegate_to: localhost  
  retries: 3
  delay: 5
  register: result           
  until: result is succeeded
  loop:
    # - "-c \"echo {{vm_password_new}} | passwd --stdin admin\""
    - "echo {{vm_password }} | sudo -S sed -i 's/managed=false/managed=true/' /etc/NetworkManager/NetworkManager.conf"
    - "echo {{vm_password }} | sudo -S service network-manager restart"
    - "echo {{vm_password }} | sudo -S nmcli dev set {{vm_eth_name}} managed yes"
    - "echo {{vm_password }} | sudo -S hostnamectl set-hostname {{ vm_hostname }}.{{ vm_domain }}"
    - "echo {{vm_password }} | sudo -S nmcli connection modify {{vm_eth_name}} IPv4.address {{vm_address}}/{{vm_netmask_cidr}} IPv4.gateway {{vm_gateway}} IPv4.method manual"
    - "echo {{vm_password }} | sudo -S nmcli connection modify {{vm_eth_name}} IPv4.dns {{vm_dns_server}}"

#   - name: Wait for VMware tools to become available by name
#     community.vmware.vmware_guest_tools_wait:
#       hostname: '{{ vcenter_address }}'
#       username: '{{ vcenter_username }}'
#       password: '{{ vcenter_password }}'    
#       validate_certs: no 
#       name: '{{ vm_name }}'
#     delegate_to: localhost
#     retries: 3
#     delay: 15
#     register: result           
#     until: result is succeeded 

#   - name: Wait for 30 seconds for VMware Tools refresh
#     wait_for: timeout=30
#     delegate_to: localhost
#   when: (checkhostname is failed) or (checkselinux is failed)
# ###end: reboot guest

# - name: Install xRDP
#   community.vmware.vmware_vm_shell:
#     hostname: '{{ vcenter_address }}'
#     username: '{{ vcenter_username }}'
#     password: '{{ vcenter_password }}'   
#     validate_certs: no 
#     vm_username: "{{ vm_username | default('root') }}"
#     vm_password: '{{ vm_password }}'
#     vm_id: '{{ vm_name }}'
#     vm_shell: '/usr/bin/sh'
#     vm_shell_args: " -c \"{{item}}\""
#     wait_for_process: true
#   delegate_to: localhost  
#   retries: 3
#   delay: 5
#   register: result           
#   until: result is succeeded
#   ignore_errors: true 
#   loop:
#     - "{{dnf_or_yum}} install -y epel-release"
#     - "{{dnf_or_yum}} install -y xrdp"
#     - "xrdp-keygen xrdp auto"
#     - "systemctl enable xrdp --now"
#     - "firewall-cmd --permanent --add-port=3389/tcp"
#     - "firewall-cmd --reload"
#   when: install_xrdp|default(false)

# - name: Install Ansible and related components
#   community.vmware.vmware_vm_shell:
#     hostname: '{{ vcenter_address }}'
#     username: '{{ vcenter_username }}'
#     password: '{{ vcenter_password }}'   
#     validate_certs: no 
#     vm_username: "{{ vm_username | default('root') }}"
#     vm_password: '{{ vm_password }}'
#     vm_id: '{{ vm_name }}'
#     vm_shell: '/usr/bin/sh'
#     vm_shell_args: " -c \"{{item}}\""
#     wait_for_process: true
#   delegate_to: localhost  
#   retries: 3
#   delay: 5
#   register: result           
#   until: result is succeeded
#   ignore_errors: true 
#   loop:
#     - "{{dnf_or_yum}} install -y epel-release"
#     - "{{dnf_or_yum}} install -y ansible"
#     - "{{dnf_or_yum}} install -y python3-pip"
#     - "{{dnf_or_yum}} install -y python3-devel"
#     - "{{dnf_or_yum}} groupinstall -y 'development tools'"
#     - "pip3 install --upgrade pip"
#     - "pip3 install netapp-lib"
#     - "pip3 install pyvmomi"
#     - "pip3 install pywinrm"
#     - "pip3 install pycdlib" 
#   when: install_ansible|default(false)

- name: Run extra shell command via vm_shell
  community.vmware.vmware_vm_shell:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    vm_username: "{{ vm_username | default('root') }}"
    vm_password: '{{ vm_password }}'
    vm_id: "{{ vm_name }}"
    vm_shell: '/usr/bin/sh'
    vm_shell_args: " -c \"{{item}}\""
    wait_for_process: true
    timeout: 3600
  delegate_to: localhost
  retries: 3
  delay: 60
  register: result
  until: result is succeeded
  ignore_errors: true
  loop: "{{ extra_commands }}"
  when:
    - extra_commands is defined
